### ISSUE TITLE
Copying results from a query containing OPTIONAL seems to cause problems

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/sparql-query-plugin#16]
From the mailing list:

When I run a SPARQL query with the OPTIONAL keyword, I can't get the SPARQL
Query Tab results into my copy buffer. See below queries and attached
ontology. Should this be logged as a bug?

Query1 yields 3 results, all of which I can copy & paste into a spreadsheet.
Query2 yields 4 results, because it includes 1 candidate (Tom) even though
he has no credentials (see pic). When I try to copy all 4, the content of my
copy buffer does not update at all (it contains whatever was in it last). I
can copy 1 row at a time, except for Tom's. Or I can select the 3 rows other
than Tom's all at once and copy them.

== Query1 ==
PREFIX CC: <http://www.somesite.com/candidateCredentials#>
SELECT ?candidate ?credential
	WHERE { ?candidate rdf:type CC:Candidate .
                             ?candidate CC:hasCredential ?credential . 
                  }

== Query 2 ==
PREFIX CC: <http://www.somesite.com/candidateCredentials#>
SELECT ?candidate ?credential
	WHERE { ?candidate rdf:type CC:Candidate .
                             OPTIONAL {?candidate CC:hasCredential
?credential}   
                  }
                 ORDER BY ASC(?candidate)

CandidateCredentials.owl
<http://protege-project.136.n4.nabble.com/file/t376492/CandidateCredentials.owl>  
SPARQL-with-OPTIONAL.png
<http://protege-project.136.n4.nabble.com/file/t376492/SPARQL-with-OPTIONAL.png>

**Comment by efenzl** [comment]
We are having this same problem and it's been 5 years now - has there been any update on this issue?
Note: The issue appears not to be a caused by the OPTIONAL part of the query, but by having blanks in the query results.

**Comment by fanavarro** [comment]
Hi, I've been experiencing problems with this as well.

I am using protege 5.5 and I am querying my ontology through the SPARQL tab. I'm copying the results to a spreadsheet, and it works fine.

Nonetheless when I use an "optional" clause in my query, my resulting rows may contain empty cells, which is the expected behaviour. Then, when I try to copy any of the rows with empty cells, a null pointer exception is thrown. For example, in the next figure I am trying to copy one of this kind of rows, and you can see that an error happened in the log at the bottom right:

![imagen](https://user-images.githubusercontent.com/11376639/230057666-29e7b1e7-a701-4290-bf37-4a73b62f6641.png)

The log is the following:

```
ERROR  12:07:03  Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NullPointerException: null
	at org.protege.editor.owl.ui.action.CopyAction.handleCopy(CopyAction.java:126) ~[na:na]
	at org.protege.editor.owl.ui.action.CopyAction.actionPerformed(CopyAction.java:99) ~[na:na]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) ~[na:1.8.0_121]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) ~[na:1.8.0_121]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) ~[na:1.8.0_121]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) ~[na:1.8.0_121]
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376) ~[na:1.8.0_121]
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356) ~[na:1.8.0_121]
	at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:802) ~[na:1.8.0_121]
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663) ~[na:1.8.0_121]
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882) ~[na:1.8.0_121]
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:699) ~[na:1.8.0_121]
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706) ~[na:1.8.0_121]
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706) ~[na:1.8.0_121]
	at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:677) ~[na:1.8.0_121]
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307) ~[na:1.8.0_121]
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:293) ~[na:1.8.0_121]
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974) ~[na:1.8.0_121]
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966) ~[na:1.8.0_121]
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845) ~[na:1.8.0_121]
	at java.awt.Component.processEvent(Component.java:6310) ~[na:1.8.0_121]
	at java.awt.Container.processEvent(Container.java:2236) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[na:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_121]
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954) ~[na:1.8.0_121]
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806) ~[na:1.8.0_121]
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074) ~[na:1.8.0_121]
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945) ~[na:1.8.0_121]
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEventImpl(Component.java:4760) ~[na:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_121]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_121]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[na:1.8.0_121]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) ~[na:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[na:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[na:1.8.0_121]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_121]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_121]
```
I think, at some point the cell needs to be rendered, but empty cells are null, so the null pointer exception is thrown. I think this could be fixed easily by checking if the cell is null, in which case it would be rendered as an empty string or something like that.
