### ISSUE TITLE
SPARQL Federation throws `HttpMethod ClassNotFoundException`

### ISSUE THREAD

**Issue by schivmeister** [protegeproject/sparql-query-plugin#18]
Is federation supposed to work? From the looks of it, it is. The SERVICE keyword invokes Sesame's FederatedServiceManager, but there is certainly something wrong with the packaging or runtime state of the plug-in or Protege. This is a freshly downloaded Protege complete bundle of the latest 5.5.0 Beta-7.

```
  ERROR  01:59:36  Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NoClassDefFoundError: org/apache/commons/httpclient/HttpMethod
	at org.openrdf.repository.sparql.SPARQLRepository.createHTTPClient(SPARQLRepository.java:92) ~[na:na]
	at org.openrdf.repository.sparql.SPARQLRepository.<init>(SPARQLRepository.java:78) ~[na:na]
	at org.openrdf.repository.sparql.SPARQLRepository.<init>(SPARQLRepository.java:58) ~[na:na]
	at org.openrdf.query.algebra.evaluation.federation.SPARQLFederatedService.<init>(SPARQLFederatedService.java:121) ~[na:na]
	at org.openrdf.query.algebra.evaluation.federation.FederatedServiceManager.getService(FederatedServiceManager.java:129) ~[na:na]
	at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:301) ~[na:na]
	at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:586) ~[na:na]
	at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:197) ~[na:na]
	at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:662) ~[na:na]
	at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:577) ~[na:na]
	at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:197) ~[na:na]
	at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:689) ~[na:na]
	at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:589) ~[na:na]
	at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:197) ~[na:na]
	at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:607) ~[na:na]
	at org.openrdf.query.algebra.evaluation.impl.EvaluationStrategyImpl.evaluate(EvaluationStrategyImpl.java:197) ~[na:na]
	at org.openrdf.sail.memory.MemoryStoreConnection.evaluateInternal(MemoryStoreConnection.java:163) ~[na:na]
	at org.openrdf.sail.helpers.SailConnectionBase.evaluate(SailConnectionBase.java:298) ~[na:na]
	at org.openrdf.repository.sail.SailTupleQuery.evaluate(SailTupleQuery.java:60) ~[na:na]
	at org.openrdf.repository.sail.SailTupleQuery.evaluate(SailTupleQuery.java:75) ~[na:na]
	at org.protege.editor.owl.rdf.repository.BasicSparqlReasoner.handleTupleQuery(BasicSparqlReasoner.java:96) ~[na:na]
	at org.protege.editor.owl.rdf.repository.BasicSparqlReasoner.executeQuery(BasicSparqlReasoner.java:71) ~[na:na]
	at org.protege.editor.owl.rdf.SparqlQueryView.lambda$createBottomComponent$0(SparqlQueryView.java:67) ~[na:na]
	at org.protege.editor.owl.rdf.SparqlQueryView$$Lambda$192/1290596935.actionPerformed(Unknown Source) ~[na:na]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) ~[na:1.8.0_40]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346) ~[na:1.8.0_40]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) ~[na:1.8.0_40]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) ~[na:1.8.0_40]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) ~[na:1.8.0_40]
	at java.awt.Component.processMouseEvent(Component.java:6525) ~[na:1.8.0_40]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[na:1.8.0_40]
	at java.awt.Component.processEvent(Component.java:6290) ~[na:1.8.0_40]
	at java.awt.Container.processEvent(Container.java:2234) ~[na:1.8.0_40]
	at java.awt.Component.dispatchEventImpl(Component.java:4881) ~[na:1.8.0_40]
	at java.awt.Container.dispatchEventImpl(Container.java:2292) ~[na:1.8.0_40]
	at java.awt.Component.dispatchEvent(Component.java:4703) ~[na:1.8.0_40]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898) ~[na:1.8.0_40]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533) ~[na:1.8.0_40]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462) ~[na:1.8.0_40]
	at java.awt.Container.dispatchEventImpl(Container.java:2278) ~[na:1.8.0_40]
	at java.awt.Window.dispatchEventImpl(Window.java:2750) ~[na:1.8.0_40]
	at java.awt.Component.dispatchEvent(Component.java:4703) ~[na:1.8.0_40]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751) ~[na:1.8.0_40]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_40]
	at java.awt.EventQueue$3.run(EventQueue.java:702) ~[na:1.8.0_40]
	at java.awt.EventQueue$3.run(EventQueue.java:696) ~[na:1.8.0_40]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86) ~[na:1.8.0_40]
	at java.awt.EventQueue$4.run(EventQueue.java:724) ~[na:1.8.0_40]
	at java.awt.EventQueue$4.run(EventQueue.java:722) ~[na:1.8.0_40]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) ~[na:1.8.0_40]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721) ~[na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_40]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_40]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.httpclient.HttpMethod not found by org.protege.owl.rdf [29]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1574) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018) ~[org.apache.felix.main.jar:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_40]
	... 60 common frames omitted
```

Please reproduce with the following:

```
select * {
  service <https://query.wikidata.org/sparql> { 
    ?s a owl:Class .
  }
} limit 10
```

**Comment by schivmeister** [comment]
@matthewhorridge Any thoughts here or does this belong in the protege issue tracker?

**Comment by matthewhorridge** [comment]
@schivmeister it looks like a required dependency can't be found at runtime.  I need to figure out where the problem lies.

**Comment by matthewhorridge** [comment]
@schivmeister after fiddling about with OSGi bundles and dependencies, I've finally got this to work.  I don't think the original plugin was meant to support federated queries... 

However, I'm just wondering if this really makes sense, since, your above query doesn't really have anything to do with the contents of Protege.  What's loaded in Protege should be the limit of what's queried.... I think (currently)

**Comment by schivmeister** [comment]
@matthewhorridge This report was motivated by a couple of users who I had to provide support to. Personally, I did try it myself in the past but dismissed it as just something that "didn't work".

For some, Protege is the first introduction to the world of both RDF and OWL, and the SPARQL window is all they know about SPARQL. They become frustrated when things don't work as expected.

So, if a tool directly or indirectly (via a library) claims to support SPARQL 1.1, breaking features arbitrarily is an unexpected behaviour. So if it's a matter of dependency resolution, why not "fix" it?
