### ISSUE TITLE
Exporting SPARQL query results would be a really useful feature

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/sparql-query-plugin#2]
Several people requested the functionality to export SPARQL query results.

As this mailing list post points out, exporting to a file/ontology of SPARQL CONSTRUCT queries, would be especially useful:
http://thread.gmane.org/gmane.comp.misc.ontology.protege.owl/40190

**Comment by ansell** [comment]
If the system is already based on RDFHandler, then any Rio RDFWriter will be able to be transparently substituted, as all RDFWriters are RDFHandlers.

That comment is just based on looking at the following, without any context around that:

https://github.com/protegeproject/org.protege.editor.owl.rdf/blob/master/src/main/java/org/protege/editor/owl/rdf/repository/GraphQueryHandler.java

**Comment by csnyulas** [comment]
Fixing [this issue](https://github.com/protegeproject/protege/issues/424), provides a way to save the results of SPARQL queries by selecting them (either one row at a time or all rows with CTRL+A) and then copying them in the clipboard with CTRL+C. You can then paste the content of the clipboard it in any text editor with CTRL+V for review, further processing or saving.

Note: Mac users would should use the ⌘+C / ⌘+V combinations.

This is available starting with Protege version 5.0.0-RC2.

**Comment by csnyulas** [comment]
This does work @llchristopherson. At least in Protege 5.1.
I created a movie that shows this: https://youtu.be/66qrsjNy_Ws

**Comment by llchristopherson** [comment]
That’s great … if you are using Linux which you are in this video. This does not work on a mac.

**Comment by llchristopherson** [comment]
I just tried the snap one – that works. Thanks. You might want to mention in the video that the snap one is the only one that lets you copy/paste the results. I really appreciate you’re doing this!!

**Comment by csnyulas** [comment]
Are you using Protege 5.1? I just tested on a Mac and it does work. Of course you will need to use `CMD+C`/`CMD+V` on a Mac, instead of `CTRL+C`/`CTRL+V`. You just need to be in the result table panel when you press the `CTRL+C` (`CMD+C` on the Mac). If you are in the query editor panel, you would copy the query, not the result. I hope this makes sense.

**Comment by llchristopherson** [comment]
Ah no, it is 5.0. I should do an update. The snap tab works wonderfully though. Thanks so much!!

**Comment by csnyulas** [comment]
I am glad it works.

**Comment by arwork** [comment]
Ctrl+C works but is not obvious, because the Edit->Copy menu item is grayed out while in the SPARQL window, implying that Copy is not available.

**Comment by csnyulas** [comment]
Interesting. I am not sure how easy it is to fix this properly, but it would be nice, indeed, if we could fix this in one of the next releases.

**Comment by csnyulas** [comment]
Same observation was made also on the mailing list:
http://protege-project.136.n4.nabble.com/Export-all-Individuals-and-their-Data-Properties-including-inferred-ones-to-a-JSON-or-XML-file-td4667012.html#a4667035

Maybe the best (and potentially easier) solution would be to fix this issue properly, for example by adding an "Export results" button.

**Comment by neilotte** [comment]
I'm on a mac using Protege 5.2 and having the same issue as @llchristopherson. I've tried both using hot keys and using the menu 'copy'. The issue is that the SPARQL return will not copy to my clipboard. 

Note: This doesn't happen every time. Sometimes I am able to copy from the return, and other times not, and its unclear to me what causes the issue. This is very frustrating.

**Comment by fanavarro** [comment]
Hi, I'm not very sure if I should open a new issue for this, or to join the conversation here. I am using protege 5.5 and I am querying my ontology through the SPARQL tab. I'm copying the results to a spreadsheet, and it works fine, although I would prefer an export button somewhere... 

Nonetheless I've discovered an issue. When I use an "optional" clause in my query, my resulting rows may contain empty cells, which is the expected behaviour. Then, when I try to copy any of the rows with empty cells, a null pointer exception is thrown. For example, in the next figure I am trying to copy one of this kind of rows, and you can see that an error happened in the log at the bottom right:

![imagen](https://user-images.githubusercontent.com/11376639/230057666-29e7b1e7-a701-4290-bf37-4a73b62f6641.png)

The log is the following:

```
ERROR  12:07:03  Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NullPointerException: null
	at org.protege.editor.owl.ui.action.CopyAction.handleCopy(CopyAction.java:126) ~[na:na]
	at org.protege.editor.owl.ui.action.CopyAction.actionPerformed(CopyAction.java:99) ~[na:na]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) ~[na:1.8.0_121]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) ~[na:1.8.0_121]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) ~[na:1.8.0_121]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) ~[na:1.8.0_121]
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376) ~[na:1.8.0_121]
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356) ~[na:1.8.0_121]
	at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:802) ~[na:1.8.0_121]
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663) ~[na:1.8.0_121]
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882) ~[na:1.8.0_121]
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:699) ~[na:1.8.0_121]
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706) ~[na:1.8.0_121]
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:706) ~[na:1.8.0_121]
	at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:677) ~[na:1.8.0_121]
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307) ~[na:1.8.0_121]
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:293) ~[na:1.8.0_121]
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974) ~[na:1.8.0_121]
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966) ~[na:1.8.0_121]
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845) ~[na:1.8.0_121]
	at java.awt.Component.processEvent(Component.java:6310) ~[na:1.8.0_121]
	at java.awt.Container.processEvent(Container.java:2236) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[na:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_121]
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954) ~[na:1.8.0_121]
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806) ~[na:1.8.0_121]
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074) ~[na:1.8.0_121]
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945) ~[na:1.8.0_121]
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEventImpl(Component.java:4760) ~[na:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_121]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_121]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[na:1.8.0_121]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) ~[na:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[na:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[na:1.8.0_121]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_121]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_121]
```
I think, at some point the cell needs to be rendered, but empty cells are null, so the null pointer exception is thrown. I think this could be fixed easily by checking if the cell is null, in which case it would be rendered as an empty string or something like that.
