### ISSUE TITLE
SPARQL query tab blank in Protege Desktop 5.6.1

### ISSUE THREAD

**Issue by regineheberlein** [protegeproject/sparql-query-plugin#22]
Is this plugin no longer being maintained? It doesn't appear to be functional for v. 5.6.1. All I get is a blank tab. (Tried re-installing the plugin, tried re-installing Protege).

**Comment by vijaykd** [comment]
I have the same issue. How do we fix it?

**Comment by ProfTuan** [comment]
I am also having the same issue.

I am using Protege 5.6.1 and 3.0v of the Sparql Plugin
```

ERROR  15:37:39  Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NoSuchMethodError: 'void org.semanticweb.owlapi.rdf.model.AbstractTranslator.<init>(org.semanticweb.owlapi.model.OWLOntologyManager, org.semanticweb.owlapi.model.OWLOntology, boolean, org.semanticweb.owlapi.util.IndividualAppearance, org.semanticweb.owlapi.util.AxiomAppearance, java.util.concurrent.atomic.AtomicInteger, java.util.Map)'
	at org.protege.owl.rdf.impl.RDFTranslator.<init>(RDFTranslator.java:107) ~[na:na]
	at org.protege.owl.rdf.impl.RDFTranslator.translate(RDFTranslator.java:55) ~[na:na]
	at org.protege.owl.rdf.impl.OwlTripleStoreImpl.addAxiom(OwlTripleStoreImpl.java:99) ~[na:na]
	at org.protege.owl.rdf.Utilities.loadOwlTripleStore(Utilities.java:48) ~[na:na]
	at org.protege.owl.rdf.Utilities.getOwlTripleStore(Utilities.java:32) ~[na:na]
	at org.protege.editor.owl.rdf.repository.BasicSparqlReasoner.precalculate(BasicSparqlReasoner.java:54) ~[na:na]
	at org.protege.editor.owl.rdf.SparqlQueryView.initializeReasoner(SparqlQueryView.java:34) ~[na:na]
	at org.protege.editor.owl.rdf.SparqlQueryView.initialiseOWLView(SparqlQueryView.java:24) ~[na:na]
	at org.protege.editor.owl.ui.view.AbstractOWLViewComponent.initialise(AbstractOWLViewComponent.java:43) ~[na:na]
	at org.protege.editor.core.ui.view.View.createContent(View.java:413) ~[na:na]
	at org.protege.editor.core.ui.view.View.createUI(View.java:220) ~[na:na]
	at org.protege.editor.core.ui.view.View$1.hierarchyChanged(View.java:124) ~[na:na]
	at java.desktop/java.awt.Component.processHierarchyEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.processEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.processEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.createHierarchyEvents(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.createHierarchyEvents(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.createHierarchyEvents(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.createHierarchyEvents(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.createHierarchyEvents(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.createHierarchyEvents(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.show(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.show(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.setVisible(Unknown Source) ~[na:na]
	at java.desktop/javax.swing.JComponent.setVisible(Unknown Source) ~[na:na]
	at java.desktop/javax.swing.JTabbedPane.fireStateChanged(Unknown Source) ~[na:na]
	at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(Unknown Source) ~[na:na]
	at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(Unknown Source) ~[na:na]
	at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(Unknown Source) ~[na:na]
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(Unknown Source) ~[na:na]
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(Unknown Source) ~[na:na]
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(Unknown Source) ~[na:na]
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(Unknown Source) ~[na:na]
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source) ~[na:na]
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.processEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.processEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source) ~[na:na]
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[na:na]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source) ~[na:na]
```

**Comment by yasenstar** [comment]
I see same issue in Protege 5.6.2

**Comment by vChavezB** [comment]
I was checking the dependencies of the sparql query plugin. It seems the error is because the latest version of this plugin useds java protege editor dependencies for version 5.5.0.  This means this plugin is only compatible at the moment with version 5.5.0 of protege.

Unless the mantainers update the dependencies the plugin is not usable with version 5.6.x.
